/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemMapRouteImport } from './routes/system-map'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SafetyCardRouteImport } from './routes/safety-card'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as GreenRouteImport } from './routes/green'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'

const SystemMapRoute = SystemMapRouteImport.update({
  id: '/system-map',
  path: '/system-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyCardRoute = SafetyCardRouteImport.update({
  id: '/safety-card',
  path: '/safety-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenRoute = GreenRouteImport.update({
  id: '/green',
  path: '/green',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/green': typeof GreenRoute
  '/passport': typeof PassportRoute
  '/safety-card': typeof SafetyCardRoute
  '/stories': typeof StoriesRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/system-map': typeof SystemMapRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/green': typeof GreenRoute
  '/passport': typeof PassportRoute
  '/safety-card': typeof SafetyCardRoute
  '/subscribe': typeof SubscribeRoute
  '/system-map': typeof SystemMapRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/green': typeof GreenRoute
  '/passport': typeof PassportRoute
  '/safety-card': typeof SafetyCardRoute
  '/stories': typeof StoriesRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/system-map': typeof SystemMapRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/green'
    | '/passport'
    | '/safety-card'
    | '/stories'
    | '/subscribe'
    | '/system-map'
    | '/stories/$slug'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/green'
    | '/passport'
    | '/safety-card'
    | '/subscribe'
    | '/system-map'
    | '/stories/$slug'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/green'
    | '/passport'
    | '/safety-card'
    | '/stories'
    | '/subscribe'
    | '/system-map'
    | '/stories/$slug'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GreenRoute: typeof GreenRoute
  PassportRoute: typeof PassportRoute
  SafetyCardRoute: typeof SafetyCardRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  SystemMapRoute: typeof SystemMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-map': {
      id: '/system-map'
      path: '/system-map'
      fullPath: '/system-map'
      preLoaderRoute: typeof SystemMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-card': {
      id: '/safety-card'
      path: '/safety-card'
      fullPath: '/safety-card'
      preLoaderRoute: typeof SafetyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green': {
      id: '/green'
      path: '/green'
      fullPath: '/green'
      preLoaderRoute: typeof GreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
  }
}

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GreenRoute: GreenRoute,
  PassportRoute: PassportRoute,
  SafetyCardRoute: SafetyCardRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  SystemMapRoute: SystemMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
